import { test, expect } from "@playwright/test";

test("Homepage", async ({ page }) => {
  await page.goto("https://inrbonds.com/");
  await page.getByRole("link", { name: "INRBonds High-Yield Corporate" }).click();
  await expect.soft(page.locator("h1")).toContainText("INRBonds High-Yield Corporate Bond Index (HCB Index)");
  await page.goto('https://inrbonds.com/');
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(1).click();
  await page.goto('https://inrbonds.com/');
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(2).click();
  await page.goto('https://inrbonds.com/');
  await page.getByRole("link", { name: "About Us" }).click();
  await page.goto("https://inrbonds.com/");
  await page.getByRole("link", { name: "Training" }).click();
  await page.goto("https://inrbonds.com/");
  await page.getByRole("link", { name: "Contact Us" }).nth(1).click();
  await page.goto("https://inrbonds.com/");
  await page.getByRole("link", { name: "MarketWatch" }).click();
  await page.goto("https://inrbonds.com/");
  await page.getByRole("link", { name: "X (Twitter)" }).click();
  await page.goto("https://inrbonds.com/");
  await page.getByRole("link", { name: "LinkedIn" }).click();
  await page.goto("https://inrbonds.com/");
  await page.getByRole("link", { name: "YouTube" }).click();
  await page.goto("https://inrbonds.com/");
  await page.getByRole("link", { name: "Terms and Conditions" }).click();
  await page.goto("https://inrbonds.com/");
  await page.getByRole("link", { name: "Privacy Policy" }).click();
  await page.goto("https://inrbonds.com/");
  await page.getByRole("link", { name: "Mandatory Disclosures" }).click();
  await page.goto("https://inrbonds.com/");
  await page.getByRole("link", { name: "Investor Charter" }).click();
  await page.goto("https://inrbonds.com/");
  // const page1Promise = page.waitForEvent("popup");
  // await page.getByRole("link", { name: "https://scores.sebi.gov.in/" }).click();
  // await page.goto("https://inrbonds.com/");
  // const page1 = await page1Promise;
  await page.getByRole("link").first().click();
});
